version: "3.1"
services:
  api:
    build: .
    container_name: price_service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/price_service
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db
    ports:
      - "8080:8080"


  db:
    image: postgres:14.7-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: price_service
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: "/var/lib/postgresql/data"
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data