INSERT INTO products(name, brands_id, categories_id)
VALUES ('Хлеб бородинский',
        (SELECT brands.id FROM brands WHERE brands.name = 'Сормовский хлеб'),
        (SELECT categories.id FROM categories WHERE categories.name = 'Хлебобулочные изделия')),
       ('Батон белый',
        (SELECT brands.id FROM brands WHERE brands.name = 'Сормовский хлеб'),
        (SELECT categories.id FROM categories WHERE categories.name = 'Хлебобулочные изделия')),
       ('Хлеб бородинский',
        (SELECT brands.id FROM brands WHERE brands.name = 'Арзамаский хлеб'),
        (SELECT categories.id FROM categories WHERE categories.name = 'Хлебобулочные изделия')),
       ('Батон белый',
        (SELECT brands.id FROM brands WHERE brands.name = 'Арзамаский хлеб'),
        (SELECT categories.id FROM categories WHERE categories.name = 'Хлебобулочные изделия')),
       ('Хлеб бородинский',
        (SELECT brands.id FROM brands WHERE brands.name = 'Каравай'),
        (SELECT categories.id FROM categories WHERE categories.name = 'Хлебобулочные изделия')),
       ('Батон белый',
        (SELECT brands.id FROM brands WHERE brands.name = 'Каравай'),
        (SELECT categories.id FROM categories WHERE categories.name = 'Хлебобулочные изделия'));

INSERT INTO products(name, brands_id, categories_id)
VALUES ('Молоко',
        (SELECT brands.id FROM brands WHERE brands.name = 'Городецкий молочный завод'),
        (SELECT categories.id FROM categories WHERE categories.name = 'Молочная продукция')),
       ('Творог',
        (SELECT brands.id FROM brands WHERE brands.name = 'Городецкий молочный завод'),
        (SELECT categories.id FROM categories WHERE categories.name = 'Молочная продукция')),
       ('Молоко',
        (SELECT brands.id FROM brands WHERE brands.name = 'Домик в деревне'),
        (SELECT categories.id FROM categories WHERE categories.name = 'Молочная продукция')),
       ('Творог',
        (SELECT brands.id FROM brands WHERE brands.name = 'Домик в деревне'),
        (SELECT categories.id FROM categories WHERE categories.name = 'Молочная продукция')),
       ('Молоко',
        (SELECT brands.id FROM brands WHERE brands.name = 'Простоквашино'),
        (SELECT categories.id FROM categories WHERE categories.name = 'Молочная продукция')),
       ('Творог',
        (SELECT brands.id FROM brands WHERE brands.name = 'Простоквашино'),
        (SELECT categories.id FROM categories WHERE categories.name = 'Молочная продукция'));

